Featureページの翻訳
vuejs-jp/vite-docs-ja pull request #10
Opened 2021-03-01 13:04 UTC by takurinton

https://github.com/vuejs-jp/vite-docs-ja/issues/9

2021-03-01 13:59 UTC, takurinton commented
Hot Module Replacement は日本語にすると何になるんだろう．固有名詞かな．

2021-03-01 16:30 UTC, shuuji3 commented
> Hot Module Replacement は日本語にすると何になるんだろう．固有名詞かな．

私は今のように英語のままにしておくのがわかりやすいと思いました。

他のドキュメントでも英語のままにしているものが見つかります。

- https://vuex.vuejs.org/ja/guide/hot-reload.html
- https://ja.parceljs.org/hmr.html

解説記事などでも英語で説明しているものが多い印象です。

2021-03-01 21:46 UTC, takurinton commented
@shuuji3 
なるほど．迷ってたのでありがたいです🙇‍♂️

2021-03-02 14:36 UTC, takurinton commented
またまたなんですけど，dynamic import はダイナミックインポートでいいですかね？？

2021-03-02 14:49 UTC, takurinton commented
@kazupon 
Featuresページの翻訳をしたのでお手隙の際にレビューの方よろしくお願いします．

2021-03-04 09:14 UTC, kazupon requested changes
レビュー 👀 しました。
確認お願いします！

2021-03-04 09:14 UTC, kazupon commented on guide/features.md
> +## NPM の依存関係の解決と先読みされるバンドル
`Pre-bundling` の訳ですが、`Pre` はどちらかというと前もって事前に何かするという意味なので、ここでは、`事前`としておいた方がよさそうです。`先読み` は何らかの高度なアルゴリズムによって処理しているようなことを示唆してしまうので。
以降で、訳されている`Pre-bundling`の部分も同様です。

2021-03-04 09:14 UTC, kazupon commented on guide/features.md
> +**依存関係は強力にキャッシュされます**
`Strongly` の訳は、`強力`では違和感があるので、ここでは意訳気味に、`ほぼ` という訳にした方がいいと思います。

2021-03-04 09:14 UTC, kazupon commented on guide/features.md
> +`.jsx` と `.tsx` もすぐにサポートされます。 JSX のトランスパイルも [ESBuild](https://esbuild.github.io) を介して行われます, デフォルトはReact16フレーバーですが、ESBuildでのReact17スタイルのJSXサポートが追跡されます。[詳しくはこちら](https://github.com/evanw/esbuild/issues
`out of the box`の訳は、この文章でのコンテキストでは、`標準` での方が日本語的違和感がない感じになると思います。

2021-03-04 09:14 UTC, kazupon commented on guide/features.md
> +- The glob matching is done via `fast-glob` - check out its documentation for
ここ、翻訳の参考のため？だと思うんですが、原文が残っているので、削除お願いしいます！

2021-03-04 09:14 UTC, kazupon commented on guide/features.md
> +## Web ワーカー
タイトルの `Web Workers` は固有名詞なので、原文のままでいいと思います。

2021-03-04 09:14 UTC, kazupon commented on guide/features.md
> +Vite は、コード分割ポイントとして ES ダイナミックインポートを使用します。 生成されたコードは、ダイナミックインポートを使用して非同期チャンクもロードします。 しかし、ネイティブ ESM ダイナミックインポートサポートは、スクリプトタグを介して ESM よりも遅く着陸し、2つの機能の間にブラウザーサポートの不一致があります。 Vite は、軽量の[ダイナミックインポートされる Polyf
`dynamic import` はここでは、固有名詞なので、原文のままの方がよさそうな気がします。

2021-03-04 09:35 UTC, shuuji3 approved these changes

2021-03-04 09:35 UTC, shuuji3 commented on guide/features.md
> +Vite はネイティブ ESM を介して [HMR API](./api-hmr) を提供します。 HMR 機能を備えたフレームワークは、API を活用して、ページを再読み込みしたり、アプリケーションの状態を損失することなく即座に正確な更新を提供できます。 Vite は[Vue Single File Components](https://github.com/vitejs/vite/tree
細い点ですが、「Preact」の先頭のPが日本語訳では小文字になってしまっているようです。

2021-03-04 09:35 UTC, shuuji3 commented on guide/features.md
> +**依存関係は強力にキャッシュされます**
[リンク先](https://github.com/takurinton/vite-docs-ja/blob/featurepage-translate/guide/dep-pre-bundling.md#browser-cache)を読んでみて、ここで「Strongly」と言っているのは、Viteが依存関係を強くキャッシュしてしまうので、依存関係を手動で編集した場合にはキャッシュを破棄するために特別な操作が必要で注意してほしい、と言いたいからだと理解しました。

「ほぼキャッシュされる」という訳にした場合、「一部の依存関係はキャッシュされない場合がある」という意味に誤解されてしまう恐れがあるように感じます。代案として、「積極的にキャッシュされる」という訳はいかがでしょうか？

2021-03-04 09:37 UTC, shuuji3 commented
すみません、コメントするだけのつもりだったのですが、間違えてapproveしてしまいました😅

2021-03-04 09:44 UTC, kazupon commented on guide/features.md
> +**依存関係は強力にキャッシュされます**
>「ほぼキャッシュされる」という訳にした場合、「一部の依存関係はキャッシュされない場合がある」という意味に誤解されてしまう恐れがあるように感じます。代案として、「積極的にキャッシュされる」という訳はいかがでしょうか？

確かに、そうですね。提案された `積極的にキャッシュされる` に自分も 1票します。:)

2021-03-04 23:36 UTC, takurinton commented on guide/features.md
> +**依存関係は強力にキャッシュされます**
確かに
`積極的にキャッシュされる`
が一番しっくりきますね！ありがとうございます！

2021-03-04 23:37 UTC, takurinton commented
@shuuji3 さん
@kazupon さん

レビューとコメントありがとうございます！明日中には修正します！

2021-03-06 00:33 UTC, takurinton commented
修正しました🙇‍♀️

2021-03-06 04:10 UTC, kazupon approved these changes

2021-03-06 04:10 UTC, merged

2021-03-06 04:11 UTC, kazupon commented
ありがとうございます！
マージしました