Config ページ - Shared Options 前半の翻訳
vuejs-jp/vite-docs-ja pull request #115
Opened 2021-05-10 15:47 UTC by jay-es

Config ページ の Shared Options ブロック前半（84-206 行）部分を翻訳いたしましたので確認お願いいたします:pray:

 close #99 close #110

2021-05-10 15:49 UTC, jay-es commented on config/index.md
> -  project root).
#110 でここの改行を削除しているので、修正後は1行減っています

2021-05-10 15:51 UTC, jay-es commented on config/index.md
> +  - `2.0.0-beta.70` 以降、文字列の値は生の式として使用されるので、文字列の定数を定義する場合は、明示的にクオートされている必要があります（例 `JSON.stringify` を使う）。
"it needs to be explicitly quoted (e.g. with `JSON.stringify`).” の訳がこれでよいか若干自信なし

2021-05-11 11:39 UTC, naokie requested changes
レビューしました 👀 
よろしくお願いします！

2021-05-11 11:39 UTC, naokie commented on config/index.md
> +  - `2.0.0-beta.70` 以降、文字列の値は生の式として使用されるので、文字列の定数を定義する場合は、明示的にクオートされている必要があります（例 `JSON.stringify` を使う）。
たしかに…
読んでいて補足しないと難しかったので、少し足してみて、これぐらいではどうでしょう？

```suggestion
  - `2.0.0-beta.70` 以降、文字列の値は純粋な式として評価されるので、文字列の定数を定義する場合は、明示的に引用符で囲う必要があります（例 `JSON.stringify` を使う）。
```

2021-05-11 11:39 UTC, naokie commented on config/index.md
> +  例えば、`process.env.FOO` や `__APP_VERSION__` などが適しています。しかし、`process` や `global` はこのオプションに入れるべきではありません。変数は代わりにシムやポリフィルで使用できます。
```suggestion
  例えば、`process.env.FOO` や `__APP_VERSION__` などが適しています。しかし、`process` や `global` はこのオプションに入れるべきではありません。変数は代わりに Shim や Polyfill で使用できます。
```

個人的にはですが、カタカナではピンとこなかったので、一般的にも英語のままがいいかもしれません。

2021-05-11 11:39 UTC, naokie commented on config/index.md
> +  パッケージのエントリーポイントを解決するときに試行する `package.json` のフィールドのリスト。これは `exports` フィールドから解決された条件付きエクスポートよりも優先順位が低いことに注意してください。エントリーポイントが `exports` からの解決に成功した場合、main フィールドは無視されます。
```suggestion
  パッケージのエントリーポイントを解決するときに試行する `package.json` のフィールドのリスト。これは `exports` フィールドから解決された条件付きエクスポートよりも優先順位が低いことに注意してください: エントリーポイントが `exports` からの解決に成功した場合、main フィールドは無視されます。
```

翻訳ガイドに従うと、次の文とのかかり具合を明示するために「:」を残す必要があります。

2021-05-11 11:39 UTC, naokie commented on config/index.md
> +  開発環境または本番環境でサーブされる際のベースとなるパブリックパス。有効な値は次のとおりです:
```suggestion
  開発環境または本番環境で配信する際のベースとなるパブリックパス。有効な値は次のとおりです:
```

他にも serve -> サーブ となっている箇所があるのですが「ファイルをクライアントに配信する」というような使い方がほとんどなので、ここでは「配信」で統一してもよさそうです。

2021-05-12 12:03 UTC, jay-es commented on config/index.md
> +  開発環境または本番環境でサーブされる際のベースとなるパブリックパス。有効な値は次のとおりです:
そういえば「サーブ」もしっくりきていませんでした。ありがとうございます:pray:

2021-05-12 12:08 UTC, jay-es commented
@naokie 修正しましたので、ご確認よろしくお願いいたします:pray:

2021-05-12 15:23 UTC, naokie approved these changes
LGTM!

2021-05-29 09:46 UTC, merged