docs: translate the guide to using plugins
vuejs-jp/vite-docs-ja pull request #124
Opened 2021-05-12 16:16 UTC by naokie

### Description

次の2ページを翻訳しました。

https://vitejs.dev/guide/using-plugins.html
Guide > Using Plugins

https://vitejs.dev/plugins/
Plugins

2021-05-28 14:10 UTC, jay-es requested changes
レビューいたしました！

2021-05-28 14:10 UTC, jay-es commented on guide/using-plugins.md
> +Vite は、一般的な Web 開発パターンをすぐに使えるよう鬼サポートすることを目的としています。Vite や互換性のある Rollup プラグインを探す前に、 [特徴ガイド](../guide/features.md) を確認してください。 Rollup プロジェクトでプラグインが必要になる多くのケースは、 Vite ですでにカバーされています。
「鬼サポート」になっています！笑

2021-05-28 14:10 UTC, jay-es commented on guide/using-plugins.md
> +## 条件付きアプリケーション
本文が apply の話題なので「条件付きの適用」などがよいかと思いました

2021-05-28 14:10 UTC, jay-es commented on plugins/index.md
> +Vite は、一般的な Web 開発パターンをすぐに使えるよう鬼サポートすることを目的としています。Vite や互換性のある Rollup プラグインを探す前に、 [特徴ガイド](../guide/features.md) を確認してください。 Rollup プロジェクトでプラグインが必要になる多くのケースは、 Vite ですでにカバーされています。
ここにも鬼が

2021-05-29 09:35 UTC, naokie commented on guide/using-plugins.md
> +Vite は、一般的な Web 開発パターンをすぐに使えるよう鬼サポートすることを目的としています。Vite や互換性のある Rollup プラグインを探す前に、 [特徴ガイド](../guide/features.md) を確認してください。 Rollup プロジェクトでプラグインが必要になる多くのケースは、 Vite ですでにカバーされています。
へんてこなタイピングミス、見つけていただいてありがとうございます 😅

2021-05-29 09:36 UTC, naokie commented on guide/using-plugins.md
> +## 条件付きアプリケーション
ですね。
見出しだけ先に訳しちゃったので、内容とマッチしてなかったです。
ありがとうございます！

2021-05-29 16:27 UTC, jay-es approved these changes
LGTM!

2021-05-31 12:24 UTC, merged