apply vitejs/vite@b1598ce
vuejs-jp/vite-docs-ja pull request #145
Opened 2021-06-03 12:55 UTC by jay-es

close #131
vitejs/vite@b1598ce の取り込みと翻訳です

2021-06-10 12:07 UTC, naokie commented on guide/ssr.md
> +  // 代わりに ’html' を使用します。
```suggestion
  // 代わりに 'html' を使用します。
```

なにか変換されちゃってますね。

2021-06-10 12:08 UTC, naokie requested changes
1つ、マークダウン記法のミスがあったので、よろしくお願いします。

2021-06-10 14:19 UTC, jay-es commented
レビューありがとうございます:pray:
クオートが変になっていたの気づいていませんでした:bow:

2021-06-16 11:00 UTC, naokie approved these changes
LGTM!!

2021-06-16 11:00 UTC, merged