Server-Side Rendering(SSR) ページの翻訳
vuejs-jp/vite-docs-ja pull request #16
Opened 2021-03-02 14:54 UTC by takurinton

https://github.com/vuejs-jp/vite-docs-ja/issues/15

2021-03-20 12:49 UTC, takurinton commented
@kazupon 

翻訳しました．
レビューお願いします．

2021-03-20 16:19 UTC, kazupon requested changes
レビュー 👀 コメント 💬  しました。
確認お願いします！

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +:::tip ノート
`Note` は以下のように訳してもいいと思います。
```suggestion
:::tip 注意
```

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +
余分な空行が入っているようです。今後アップデートがあった際にdiff でレビューしやすくするために、なるべく原文と同じ構成にしておきましょう〜

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +ここで `vite` は [ViteDevServer](./api-javascript#vitedevserver) のインスタンスです。 `vite.middlewares` は、接続互換の Node.js フレームワークでミドルウェアとして使用できる [Connect](https://github.com/senchalabs/connect) インスタンスです。
`connect-compatible` の `connect` は Node.js HTTP サーバーフレームワークの connect の固有名詞なので、知っている人が理解できるよう、以下のようにそのままにしておいたほうがいいですね。

```suggestion
ここで `vite` は [ViteDevServer](./api-javascript#vitedevserver) のインスタンスです。 `vite.middlewares` は、connect 互換 の Node.js フレームワークでミドルウェアとして使用できる [Connect](https://github.com/senchalabs/connect) インスタンスです。
```

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +    // 6. レンダリングされた HTML を send します。
`send` を訳すなら、意訳気味に以下のようにでどうでしょうか。

```suggestion
    // 6. レンダリングされた HTML をクライアントに送ります。
```

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> -The above script will now generate `dist/client/ssr-manifest.json` for the client build (Yes, the SSR manifest is generated from the client build because we want to map module IDs to client files). T
`The manifest contains mappings of module IDs to their associated chunks and asset files.` の訳が抜けてしまっています！

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +## 外部の SSR
固有名詞が複数の単語になるケースを翻訳する場合は、特に格助詞`の`を入れると読みづらくなるので、以下のように連続で固有名詞を訳す形にしておいた方が個人的にはいいと思っています。
```suggestion
## 外部 SSR
```

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +多くの依存関係は、ESM ファイルと CommonJS ファイルの両方を出荷します。SSR を実行する場合、CommonJS ビルドを提供する依存関係を Vite の SSR トランスフォーム/モジュールシステムから外部化することで、開発とビルドの両方を高速化できます。 例えば、あらかじめバンドルされている ESM バージョンの React をプルして、Node.js 互換に戻す代わりに単純に
`then transforming` が抜けて、`pulling` の訳に違和感があったので以下のように少し変更してみました。どうでしょう？

```suggestion
多くの依存関係は、ESM ファイルと CommonJS ファイルの両方を出荷します。SSR を実行する場合、CommonJS ビルドを提供する依存関係を Vite の SSR トランスフォーム/モジュールシステムから外部化することで、開発とビルドの両方を高速化できます。 例えば、あらかじめバンドルされている ESM バージョンの React を用いて、それから変換してそれを Node.js 互換に戻す代わりに、単純に `require('react')` を使用する方が効率的です。また、SSRバンドルビルドの速度も大幅に向上します。
```

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +- 依存関係の解決された ESM エントリポイントとそのデフォルトのノードエントリポイントが異なる場合、そのデフォルトのノードエントリはおそらく外部化できる CommonJS ビルドです。例えば、`vue` は ESM ビルドと CommonJS ビルドの両方を出荷するため、自動的に外部化されます。
Node (Node.jsのことを意味している) が訳されると、逆にわかりづらくなるので、ここでは以下のようにそのままにしておく方がよさそうです。

```suggestion
- 依存関係の解決された ESM エントリポイントとそのデフォルトの Node エントリポイントが異なる場合、そのデフォルトの Node エントリはおそらく外部化できる CommonJS ビルドです。例えば、`vue` は ESM ビルドと CommonJS ビルドの両方を出荷するため、自動的に外部化されます。
```

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +将来的には、このヒューリスティックは、プロジェクトで `type: "module"` が有効になっているかどうかを検出するように改善される可能性があります。これにより、Vite は、SSR 中に動的な `import()` を介してインポートすることにより、ノード互換の ESM ビルドを出荷する依存関係を外部化することもできます。
ここも Node をそのままにしておくと、理解しやすいと思います。

```suggestion
将来的には、このヒューリスティックは、プロジェクトで `type: "module"` が有効になっているかどうかを検出するように改善される可能性があります。これにより、Vite は、SSR 中に動的な `import()` を介してインポートすることにより、Node 互換の ESM ビルドを出荷する依存関係を外部化することもできます。
```

2021-03-20 16:19 UTC, kazupon commented on guide/ssr.md
> +        // SSR 固有の変換を実行する...
ここも `transform` をそのままにしておいた方が、理解しやすいかと。
```suggestion
        // SSR 固有の transform を実行する...
```

2021-04-02 02:54 UTC, takurinton commented
@kazupon 
遅くなり申し訳ありません！レビューありがとうございます！
変更しましたので確認よろしくお願いします！🙇‍♂️

2021-05-01 16:05 UTC, kazupon approved these changes

2021-05-01 16:06 UTC, kazupon commented
@takurinton 
すいません。遅くなりました！
よさそうなのでマージします！

2021-05-01 16:06 UTC, merged