apply and translate vitejs/vite@de1ddd4
vuejs-jp/vite-docs-ja pull request #174
Opened 2021-06-26 14:52 UTC by jay-es

close #169

399879c で vitejs/vite@de1ddd4 を取り込み、
b6bbbbd で翻訳しています

when XXX is about to - がいくつかありましたが、直訳だと回りくどかったので「直前」としました。
（ニュアンス合ってるでしょうか）

2021-06-29 09:57 UTC, naokie commented on guide/api-hmr.md
> +HMR イベントをリッスンします。
```suggestion
HMR イベントを購読します。
```

イベントに対しては「購読」と訳すのが、古くからの JS 書籍で見られるのでコチラのほうが自然かもしれません。

ref.
https://github.com/vuejs-jp/ja.vuejs.org/issues/94

2021-06-29 10:01 UTC, naokie requested changes
beforeXXX なので「直前」でも意味はあってますし、単純に和訳して「〜のとき」 でもよいと思います。

2021-06-29 13:13 UTC, naokie requested changes
もう１箇所あったのでコメントしました。

2021-06-29 13:13 UTC, naokie commented on guide/api-hmr.md
> +- `'vite:beforeFullReload'` フルリロードが発生する直前
```suggestion
- `'vite:beforeFullReload'` 完全なリロードが発生する直前
```

https://github.com/jay-es/vite-docs-ja/blob/issue169/guide/api-hmr.md#L107
「a full reload」について、既存の訳があるので、表記揺れをなくしたいです。

2021-06-29 13:18 UTC, jay-es commented on guide/api-hmr.md
> +- `'vite:beforeFullReload'` フルリロードが発生する直前
表記ゆれ気づいていませんでした。ありがとうございます:pray:

2021-06-29 13:19 UTC, jay-es commented on guide/api-hmr.md
> +- `'vite:beforeFullReload'` フルリロードが発生する直前
@naokie 表記ゆれ気づいていませんでした。ありがとうございます:pray:

2021-06-30 10:28 UTC, naokie approved these changes
LGTM!

2021-06-30 10:28 UTC, merged