Config ページ Build Options 前半の翻訳
vuejs-jp/vite-docs-ja pull request #178
Opened 2021-06-26 16:13 UTC by jay-es

close #177

2021-06-26 16:17 UTC, jay-es commented on config/index.md
>    Another special value is 'esnext' - which only performs minimal transpiling (for minification compat) and assumes native dynamic imports support.
見覚えがある文だと思ったら #163 で変更が入っていた
#166 マージ後に作業再開

2021-06-30 10:43 UTC, naokie requested changes
表記揺れについてコメントしました。

2021-06-30 10:43 UTC, naokie commented on config/index.md
> +  もうひとつの特別な値は `'esnext'` で、これはネイディブのダイナミックインポートをサポートしていることを前提としており、トランスパイルが可能な限り少なくなります:
「dynamic imports」について表記揺れあるので「動的インポート」に合わせていってもいいかもしれないですね。
他にも2箇所あるので、それぞれコメントしておきます。

cf. https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports

2021-06-30 10:43 UTC, naokie commented on config/index.md
> +  [dynamic import のポリフィル](https://github.com/GoogleChromeLabs/dynamic-import-polyfill)を自動的に注入するか。
「dynamic imports」に関して、2箇所目。

2021-06-30 10:43 UTC, naokie commented on config/index.md
> +  注意: ポリフィルは[ライブラリモード](/guide/build#library-mode)には適用**されません**。ネイティブの dynamic import がないブラウザをサポートする必要がある場合は、ライブラリでの使用は避けたほうが良いでしょう。
「dynamic imports」に関して、3箇所目。

2021-06-30 12:33 UTC, jay-es commented
表記ゆれ修正しました！:pray:

2021-07-12 04:48 UTC, kazupon approved these changes
良さそうなのでマージしますね。/cc @naokie

2021-07-12 04:48 UTC, merged