HMR API ページの翻訳
vuejs-jp/vite-docs-ja pull request #27
Opened 2021-03-09 15:10 UTC by jay-es

レビューよろしくお願いします:pray:

close #20

2021-03-11 16:12 UTC, kazupon requested changes
遅くなりました。レビューコメントしましたので、確認お願いします！

2021-03-11 16:12 UTC, kazupon commented on guide/api-hmr.md
> +マニュアル HMR は主にフレームワークやツール作成者を対象としています。エンドユーザーには、HMR はフレームワーク固有のスターターテンプレート内ですでに処理されている可能性が高いです。
`likely` ですが、物事の可能性について表現している単語です。なのでここでは `可能性が高い` という訳より、意訳気味に以下のようにしたほうが自然になるかと思います。

```suggestion
マニュアル HMR は主にフレームワークやツール作成者を対象としています。エンドユーザーには、HMR はフレームワークによっては、スターターテンプレート内ですでに処理されていることがありえるでしょう。
```

2021-03-13 15:36 UTC, jay-es commented
いただいた内容をそのまま使わせていただきました:pray:

2021-03-13 16:02 UTC, kazupon approved these changes

2021-03-13 16:02 UTC, kazupon commented
ありがとうございます！

2021-03-13 16:02 UTC, merged