WIP  translate assets.md
vuejs-jp/vite-docs-ja pull request #30
Opened 2021-03-14 14:35 UTC by kazuki-komori

ref #11

2021-03-21 08:47 UTC, shuuji3 approved these changes

2021-03-21 08:47 UTC, shuuji3 commented on guide/assets.md
> +- Vue プラグインを使用している場合、 Vue の SFC テンプレートも自動的にインポートに変換されます。
この行の "asset references" の翻訳が抜けてしまっているみたいです。

他の部分も全体を通しで読んでみましたが、読みやすくて良い翻訳だと思いました🙂

2021-04-09 08:36 UTC, shuuji3 commented on guide/assets.md
> +- Vue プラグインを使用している場合、 Vue の SFC テンプレートも自動的にインポートに変換されます。
更新された翻訳で修正を確認しました:100:

2021-04-09 08:42 UTC, shuuji3 commented on guide/assets.md
> +スクリプトは末尾に `?worker` を付与することで web workers としてインポートすることができます。
```suggestion
スクリプトは末尾に `?worker` を付与することで web worker としてインポートすることができます。
```

細かいですが、日本語の場合 web worker は単数形にしてもいいかと思います。いかがでしょうか？（参考: [Web Worker の使用 - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Using_web_workers)）

2021-04-09 08:44 UTC, shuuji3 commented on guide/assets.md
> +スクリプトは末尾に `?worker` を付与することで web workers としてインポートすることができます。
同じような細かい指摘ですが、assets や Assets なども、日本語では asset で統一してもいいかもしれません。

2021-05-29 10:04 UTC, naokie requested changes
レビューしました。よろしくお願いします！

2021-05-29 10:04 UTC, naokie commented on guide/assets.md
> +# Static Asset の取り扱い
```suggestion
# 静的アセットの取り扱い
```

アセットは IT 用語として一般的なのでカタカナ表記で大丈夫ですね。
同様に動的・静的も。

2021-05-29 16:12 UTC, kazuki-komori commented on guide/assets.md
> +# Static Asset の取り扱い
レビューありがとうございます。
修正しましたのでご確認お願いします 🙇

2021-05-31 12:23 UTC, naokie approved these changes
LGTM！

2021-05-31 12:23 UTC, merged